1.  Cargad el csv que guardasteis ayer.

Antes de seguir con las preguntas, este DataFrame está terriblemente sucio. En las próximas sesiones lo iremos limpiando. Para evitar posibles errores con los nulos vamos a eliminar todos los nulos del DataFrame.

Para ello vamos a utilizar el método .dropna() de pandas. Tendréis que ejecutar la siguiente línea de código para eliminar los nulos del DataFrame y poder seguir haciendo el resto de los ejercicios.

df.dropna(inplace = True)

¿Cuántas filas se han eliminado con esta línea de código?

In [1]:
import pandas as pd
import numpy as np

Cread un array de 5x3 con números decimales aleatorios entre el 5 y el 10

In [2]:
attacks = pd.read_csv('Datos/attacks_nuevo.csv',index_col = 0)
filas, columnas = attacks.shape

In [3]:
#Trabajaremos con el archivo attacks y lo llamaremos df
df = attacks.dropna()
filas_df, columnas_df = df.shape

In [4]:
#Vemos cuantas filas hemos eliminado
print (f'Ha eiliminado {filas-filas_df} filas')

Ha eiliminado 4612 filas

In [5]:
df.head()

,year,type,country,area,location,activity,name,sex_,age,time,species_,href
case_number,,,,,,,,,,,,
2018.06.25,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.06.03.a,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,Late afternoon,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.05.26.b,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,15,17h00,"Bull shark, 6'",http://sharkattackfile.net/spreadsheets/pdf_di...
2018.05.24,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,32,Morning,Grey reef shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.05.13.a,2018.0,Invalid,ENGLAND,Cornwall,Off Land's End,Fishing,Max Berryman,M,21,08h15,Invalid incident,http://sharkattackfile.net/spreadsheets/pdf_di...

2- ¿Cuál es el número de ataques que se han producido en Estados Unidos?

In [6]:
usa = df[df['country']=='USA'] #Filtramos por la columna country donde incluya USA
usa.head()

,year,type,country,area,location,activity,name,sex_,age,time,species_,href
case_number,,,,,,,,,,,,
2018.06.25,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.05.26.b,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,15,17h00,"Bull shark, 6'",http://sharkattackfile.net/spreadsheets/pdf_di...
2018.03.31,2018.0,Unprovoked,USA,Hawaii,Kukio Beach,Stand-Up Paddleboarding,male,M,25,09h30,"Tiger shark, 12'",http://sharkattackfile.net/spreadsheets/pdf_di...
2017.12.31,2017.0,Unprovoked,USA,Hawaii,"Hultin's Beach, Oahu",Surfing,Marjorie Mariano,F,54,18h00,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2017.11.24,2017.0,Unprovoked,USA,California,"Stillwater Cove, Monterey County",Spearfishing,Grigor Azatian,M,25,13h45,"White shark, 4.6 m",http://sharkattackfile.net/spreadsheets/pdf_di...

In [7]:
usa.shape[0]
#Usamos shape para ver el número de filas. Se han producido 719 ataques en USA

719

3- ¿Y en España?
3.1 ¿En qué regiones se han producido los ataques (columna location) ?
3.2 ¿Cuántos ataques se han producido en cada área (columna area?

In [8]:
df['country'].unique() #Vemos los valores de la columna country para ver como están escritos los países

array(['USA', 'BRAZIL', 'AUSTRALIA', 'ENGLAND', 'COSTA RICA', 'MALDIVES',
       'SOUTH AFRICA', 'CUBA', 'SPAIN', 'BAHAMAS', 'INDONESIA', 'EGYPT',
       'NEW ZEALAND', 'FRENCH POLYNESIA', 'NEW CALEDONIA', 'ECUADOR',
       'THAILAND', 'REUNION', 'MEXICO', 'JAMAICA', 'ITALY',
       'PAPUA NEW GUINEA', 'RUSSIA', 'SEYCHELLES', 'VIETNAM', 'GUAM',
       'MOZAMBIQUE', 'SCOTLAND', 'UNITED KINGDOM', 'TAIWAN', 'CROATIA',
       'FIJI', 'TONGA', 'ST. MAARTIN', 'GRAND CAYMAN', 'VANUATU',
       'VENEZUELA', 'TURKS & CAICOS', 'OKINAWA', 'MARSHALL ISLANDS',
       'MAURITIUS', 'HONG KONG', 'JAPAN', 'SOUTH KOREA', 'ISRAEL',
       'MICRONESIA', 'COLUMBIA', 'NEW BRITAIN', 'PALAU',
       'SOLOMON ISLANDS', 'FEDERATED STATES OF MICRONESIA', 'GREECE',
       'BRITISH WEST INDIES', 'NORTH PACIFIC OCEAN', 'BERMUDA',
       'PHILIPPINES', 'AMERICAN SAMOA', 'PACIFIC OCEAN', 'SENEGAL',
       'ARGENTINA', 'EL SALVADOR', 'IRAQ', 'PANAMA', 'INDIA'],
      dtype=object)

In [9]:
spain = df[df['country']=='SPAIN'] #Filtramos por la columna country donde incluya SPAIN
spain.head()

,year,type,country,area,location,activity,name,sex_,age,time,species_,href
case_number,,,,,,,,,,,,
2017.08.26.b,2017.0,Invalid,SPAIN,Castellón,Grao de Moncofa,Swimming,female,F,11,Midday,Shark involvement questionable,http://sharkattackfile.net/spreadsheets/pdf_di...
2016.07.29,2016.0,Unprovoked,SPAIN,Alicante Province,Arenales del Sol,Swimming,male,M,40,11h30,Blue shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2015.08.18.a,2015.0,Invalid,SPAIN,Alicante,"Poniente Beach, Benidorm",Swimming,male,M,10,11h00,Shark involvement not confirmed,http://sharkattackfile.net/spreadsheets/pdf_di...
2010.07.16.b,2010.0,Provoked,SPAIN,Grand Canary Island,"Sardina del Norte, Gáldar",Swimming,male,M,9,19h15,Angel shark,http://sharkattackfile.net/spreadsheets/pdf_di...
1993.09.03,1993.0,Unprovoked,SPAIN,Costa Blanca,"Playa de las Arenas, Valencia",Swimming,Jorge Durich Heredia (or Hernandez),M,69,08h00,1.2 m [4'] shark,http://sharkattackfile.net/spreadsheets/pdf_di...

In [10]:
spain.shape[0]
#En España ha habido 5 ataques

5

In [11]:
#Regiones en España
spain['location'].unique()

array(['Grao de Moncofa', 'Arenales del Sol', 'Poniente Beach, Benidorm',
       'Sardina del Norte, Gáldar', 'Playa de las Arenas, Valencia '],
      dtype=object)

In [12]:
#Ataques en cada área
spain['area'].value_counts()

Castellón              1
Alicante Province      1
Alicante               1
Grand Canary Island    1
Costa Blanca           1
Name: area, dtype: int64

4- Extraed un DataFrame nuevo con los ataques que se han producido en Australia y Estados Unidos. 

📌 Nota Este ejercicio se puede resolver usando dos condiciones de filtrado o usando el método isin(). Hacedlo con ambas herramientas.

4.1 ¿Cuántos ataques se han producido en cada país?

4.2 ¿Ha habido ataques en Australia a gente que estuviera remando (lo encontrareis como Paddling en el DataFrame en la columna activity)?

4.3 ¿Cuántos ataques se han producido en Australia antes del 2000?

4.4 ¿Y después del 2000?

In [13]:
#Ataques en Australia y USA, filtramos la columna country por estos países 
aus_usa=df[(df['country']=='USA') | (df['country']=='AUSTRALIA')]
aus_usa.head()

,year,type,country,area,location,activity,name,sex_,age,time,species_,href
case_number,,,,,,,,,,,,
2018.06.25,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.05.26.b,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,15,17h00,"Bull shark, 6'",http://sharkattackfile.net/spreadsheets/pdf_di...
2018.05.24,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,32,Morning,Grey reef shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.04.25.a,2018.0,Unprovoked,AUSTRALIA,Western Australia,"Surfers Point, Prevelly",Surfing,Rob Bruce,M,60,09h30,3 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.03.31,2018.0,Unprovoked,USA,Hawaii,Kukio Beach,Stand-Up Paddleboarding,male,M,25,09h30,"Tiger shark, 12'",http://sharkattackfile.net/spreadsheets/pdf_di...

In [14]:
#Utilizando el método isin:
aus_usa2=df[df['country'].isin(['USA', 'AUSTRALIA'])]
aus_usa2.head()

,year,type,country,area,location,activity,name,sex_,age,time,species_,href
case_number,,,,,,,,,,,,
2018.06.25,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.05.26.b,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,15,17h00,"Bull shark, 6'",http://sharkattackfile.net/spreadsheets/pdf_di...
2018.05.24,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,32,Morning,Grey reef shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.04.25.a,2018.0,Unprovoked,AUSTRALIA,Western Australia,"Surfers Point, Prevelly",Surfing,Rob Bruce,M,60,09h30,3 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.03.31,2018.0,Unprovoked,USA,Hawaii,Kukio Beach,Stand-Up Paddleboarding,male,M,25,09h30,"Tiger shark, 12'",http://sharkattackfile.net/spreadsheets/pdf_di...

In [15]:
#Ataques en cada país a través de value_counts
aus_usa['country'].value_counts()

USA          719
AUSTRALIA    324
Name: country, dtype: int64

In [16]:
aus_usa[(aus_usa['country']=='AUSTRALIA')&(aus_usa['activity']=='Paddling')] #No hay ninguno haciendo Paddling en Australia

Empty DataFrame
Columns: [year, type, country, area, location, activity, name, sex_, age, time, species_, href]
Index: []

In [17]:
aus_usa[(aus_usa['country']=='AUSTRALIA')&(aus_usa['year']<2000.0)] # 151 ataques antes del año 2000 en Australia

,year,type,country,area,location,activity,name,sex_,age,time,species_,href
case_number,,,,,,,,,,,,
1999.05.29,1999.0,Unprovoked,AUSTRALIA,South Australia,"Hardwicke Bay, Yorke Peninsula",Windsurfing,Tony Donoghue,M,22,14h30,Thought to involve a white shark,http://sharkattackfile.net/spreadsheets/pdf_di...
1999.02.23,1999.0,Unprovoked,AUSTRALIA,New South Wales,Scotts Head,Surfing,male,M,35,Evening,Bronze whaler or tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...
1998.06.28.a,1998.0,Unprovoked,AUSTRALIA,South Australia,South Neptune Island,Free diving for abalone,Doug Chesser,M,26,14h00,Thought to involve a 5.5 m white shark named Kong,http://sharkattackfile.net/spreadsheets/pdf_di...
1998.01.28.R,1998.0,Invalid,AUSTRALIA,New South Wales,Whale Beach,Spearfishing,male,M,31,20h00,Shark involvement not confirmed,http://sharkattackfile.net/spreadsheets/pdf_di...
1997.11.09,1997.0,Unprovoked,AUSTRALIA,Western Australia,Albany,Scuba diving (submerged riding a scooter),Kevin Hulkes,M,42,Morning,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...
1912.01.26,1912.0,Unprovoked,AUSTRALIA,New South Wales,"Fig Tree Bridge, Lane Cove River, near Sydney",Swimming,James Edward Morgan,M,21,15h00,"2.8 m [9'3""] whaler shark captured 3 days late...",http://sharkattackfile.net/spreadsheets/pdf_di...
1905.03.26,1905.0,Unprovoked,AUSTRALIA,New South Wales,Lismore,Bathing,Richard Owen,M,40,Morning,5' shark,http://sharkattackfile.net/spreadsheets/pdf_di...
1894.11.28,1894.0,Unprovoked,AUSTRALIA,New South Wales,Newcastle,Bathing,Horace Hewison,M,19,Morning,10' to 12' shark,http://sharkattackfile.net/spreadsheets/pdf_di...
1892.03.02,1892.0,Provoked,AUSTRALIA,New South Wales,Lake Macquarie,Fishing,Christopher Wang,M,21,Night,12' shark,http://sharkattackfile.net/spreadsheets/pdf_di...
1880.11.25,1880.0,Unprovoked,AUSTRALIA,Queensland,"Petrie Bight, Brisbane River",Swimming,Alexey Drury,M,12,Afternoon,Bull shark,http://sharkattackfile.net/spreadsheets/pdf_di...

In [18]:
aus_usa[(aus_usa['country']=='AUSTRALIA')&(aus_usa['year']>2000.0)] # 167  ataques después del año 2000 en Australia

,year,type,country,area,location,activity,name,sex_,age,time,species_,href
case_number,,,,,,,,,,,,
2018.05.24,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,32,Morning,Grey reef shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.04.25.a,2018.0,Unprovoked,AUSTRALIA,Western Australia,"Surfers Point, Prevelly",Surfing,Rob Bruce,M,60,09h30,3 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.03.14,2018.0,Unprovoked,AUSTRALIA,Western Australia,Waterman's Bay,Wading,Luke Guy & Finn Bald,M,10,17h35,Wobbegong shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.03.09.b,2018.0,Unprovoked,AUSTRALIA,Victoria,Lorne,Swimming,Rob Crossland,M,69,15h30,3.5 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2018.03.09.a,2018.0,Unprovoked,AUSTRALIA,Victoria,Winkipop,Surfing,Lachie Brown,M,18,07h30,1.8 m shark,http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...
2002.02.07,2002.0,Boating,AUSTRALIA,New South Wales,Paramatta River (near Sydney),Kayaking,Paul McNamara,M,35,19h15,C. leucas tooth fragment recovered from kayak,http://sharkattackfile.net/spreadsheets/pdf_di...
2002.01.30.b,2002.0,Unprovoked,AUSTRALIA,New South Wales,Just north of Fingal Spit,Surfing,Andrew Cribb,M,20,20h45 (Sunset),"Tiger shark, 3 m [10']",http://sharkattackfile.net/spreadsheets/pdf_di...
2001.10.02,2001.0,Unprovoked,AUSTRALIA,Queensland,200 miles offshore,Snorkeling,Katherine Jones,F,20,13h00,Bronze whaler shark?,http://sharkattackfile.net/spreadsheets/pdf_di...
2001.04.02.a,2001.0,Unprovoked,AUSTRALIA,New South Wales,Nambucca River Entrance,Surfing,Richard Ellis,M,40,10h00,Bronze whaler shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2001.02.04,2001.0,Unprovoked,AUSTRALIA,New South Wales,Broome Head,Surfing,Mark Butler,M,40,16h15,"Bronze whaler shark, 2.5 m [8.25'] k",http://sharkattackfile.net/spreadsheets/pdf_di...

5- Extraed unicamente los ataques a mujeres.

In [19]:
mujeres=df[df['sex_']=='F']
mujeres.shape[0]
#207 ataques a mujeres, filtramos la columna sex_ donde los valores sean F

207

6- ¿Cuántas mujeres fueron atacadas en España?

In [20]:
mujeres[mujeres['country']=='SPAIN']
# 1 ataque a mujer en España

,year,type,country,area,location,activity,name,sex_,age,time,species_,href
case_number,,,,,,,,,,,,
2017.08.26.b,2017.0,Invalid,SPAIN,Castellón,Grao de Moncofa,Swimming,female,F,11,Midday,Shark involvement questionable,http://sharkattackfile.net/spreadsheets/pdf_di...

7- Extraed los ataques que se hayan producido en el año 2000, 1997 y 2006. Utilizad el método isin() para resolver este ejercicio.

In [21]:
años=df[df['year'].isin([2000.0, 1997.0,2006.0])]
años['year'].value_counts()

2006.0    40
2000.0    33
1997.0    19
Name: year, dtype: int64

8- Si extraemos los valores únicos de la columna species nos podemos dar cuenta que está un poco sucia y extraer informacion útil de la misma se puede convertir en algo difícil. En este ejercicio tendréis que extraer los ataques que han ocurrido por tiburón blanco (lo encontraremos en la columna species como algo que contenga white o White). Usad el método str.contains() para resolver este ejercicio.

In [22]:
patron = '.+white.+' #Creamos el patrón de regex para cualquier dato que incluya la palabra white

In [23]:
white = df[df['species_'].str.contains(patron, case = False, regex = True)] #filtramos el df con str.contains incluyendo el patron anterior y case = false para que no sea case sensitive y encuentre también White
white.head()

,year,type,country,area,location,activity,name,sex_,age,time,species_,href
case_number,,,,,,,,,,,,
2018.02.23,2018.0,Unprovoked,AUSTRALIA,New South Wales,"Little Congwong Beach, La Perouse",Swimming,Anna Shurapey,F,55,"19h00, Dusk","Juvenile white shark, 2.7 to 3.2 m",http://sharkattackfile.net/spreadsheets/pdf_di...
2015.01.06,2015.0,Unprovoked,BAHAMAS,Abaco Islands,"Tahiti Beach, Elbow Cay",Snorkeling,Lacy Webb,F,34,16h00,White shark or oceanic whitetip shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2014.10.02.a,2014.0,Unprovoked,AUSTRALIA,Western Australia,"Kelpids Beach, Wylie Bay, Esperance",Surfing,Sean Pollard,M,23,11h00,"2 white shark: 13' & 9""8""",http://sharkattackfile.net/spreadsheets/pdf_di...
2014.05.14,2014.0,Unprovoked,AUSTRALIA,South Australia,"Elliston, Eyre Peninsula",Surfing,Andrew McLeod,M,35,09h30,"white shark, 15'",http://sharkattackfile.net/spreadsheets/pdf_di...
2014.04.03,2014.0,Unprovoked,AUSTRALIA,New South Wales,Tathra,Swimming,Christine Armstrong,F,63,08h20,3 m to 4 m white shark,http://sharkattackfile.net/spreadsheets/pdf_di...

9- Extraed ahora los ataques por tiburón blanco o tigre. Utilizad el método str.contains() para resolver este ejercicio.

In [24]:
patron1 ='.+white.+|.+tiger.+' #Creamos un patrón para que encuentre todo lo que contenga white o tiger

In [25]:
white_tiger = df[df['species_'].str.contains(patron1, case = False, regex = True)] #Filtramos con el patron anterior
white_tiger.head()

,year,type,country,area,location,activity,name,sex_,age,time,species_,href
case_number,,,,,,,,,,,,
2018.02.23,2018.0,Unprovoked,AUSTRALIA,New South Wales,"Little Congwong Beach, La Perouse",Swimming,Anna Shurapey,F,55,"19h00, Dusk","Juvenile white shark, 2.7 to 3.2 m",http://sharkattackfile.net/spreadsheets/pdf_di...
2015.06.24.b,2015.0,Unprovoked,USA,North Carolina,Surf City,Swimming,Brady Noyes,M,6,12h25,Sandtiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2015.01.06,2015.0,Unprovoked,BAHAMAS,Abaco Islands,"Tahiti Beach, Elbow Cay",Snorkeling,Lacy Webb,F,34,16h00,White shark or oceanic whitetip shark,http://sharkattackfile.net/spreadsheets/pdf_di...
2014.10.02.a,2014.0,Unprovoked,AUSTRALIA,Western Australia,"Kelpids Beach, Wylie Bay, Esperance",Surfing,Sean Pollard,M,23,11h00,"2 white shark: 13' & 9""8""",http://sharkattackfile.net/spreadsheets/pdf_di...
2014.05.14,2014.0,Unprovoked,AUSTRALIA,South Australia,"Elliston, Eyre Peninsula",Surfing,Andrew McLeod,M,35,09h30,"white shark, 15'",http://sharkattackfile.net/spreadsheets/pdf_di...

10- Utilizando la columna de year cread una nueva columna llamada siglo que tiene siglo-XX o siglo-XXI. Donde el año sea menor que 2000 pondremos siglo-XX y el resto de los años siglo-XXI.

In [26]:
condiciones = [df["year"] < 2000.0, df["year"] >= 2000.0] #Creamos los filtros de los años
opciones = ["siglo-XX", "siglo-XXI"] #Creamos las opciones que incluiran las columnas

df['siglo']= np.select(condiciones, opciones) #A través de np.select creamos la columna nueva
df.head()

/tmp/ipykernel_1288/683336813.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['siglo']= np.select(condiciones, opciones) #A través de np.select creamos la columna nueva

,year,type,country,area,location,activity,name,sex_,age,time,species_,href,siglo
case_number,,,,,,,,,,,,,
2018.06.25,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,18h00,White shark,http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XXI
2018.06.03.a,2018.0,Unprovoked,BRAZIL,Pernambuco,"Piedade Beach, Recife",Swimming,Jose Ernesto da Silva,M,18,Late afternoon,Tiger shark,http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XXI
2018.05.26.b,2018.0,Unprovoked,USA,Florida,"Cocoa Beach, Brevard County",Walking,Cody High,M,15,17h00,"Bull shark, 6'",http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XXI
2018.05.24,2018.0,Provoked,AUSTRALIA,Queensland,Cairns Aquarium,Feeding sharks,male,M,32,Morning,Grey reef shark,http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XXI
2018.05.13.a,2018.0,Invalid,ENGLAND,Cornwall,Off Land's End,Fishing,Max Berryman,M,21,08h15,Invalid incident,http://sharkattackfile.net/spreadsheets/pdf_di...,siglo-XXI

In [27]:
df['siglo'].value_counts() #Comprobamos los valores del df

siglo-XXI    785
siglo-XX     717
Name: siglo, dtype: int64

11- Guardad como un archivo csv nuevo. Lo usaremos en el pair programming de mañana

In [28]:
df.to_csv('Datos/attacks_pandas4.csv')